### ISSUE TITLE
After run_optical_flow, the marker position will be misaligned

### ISSUE THREAD

**Issue by StevenGuo30** [GazzolaLab/BR2-vision-based-smoothing#3]
As shown in the first image, z4-R6 is on the rightmost marker, but after run_optical_flow, z4-R6 is even to the left of z4-R4 from the x-coordinate of the start position, which means that there is a misalignment of the marker at the beginning of the trace.

![e7cb476f887abc5b6e54aed33d71358](https://github.com/GazzolaLab/BR2-vision-based-smoothing/assets/86000876/dd5f554a-8673-4e04-a27f-a63ab8daa78a)

![9d18542885000071cb19ae6540d0a90](https://github.com/GazzolaLab/BR2-vision-based-smoothing/assets/86000876/54a7f262-0563-44a0-b0b6-484503afd30d)

**Comment by StevenGuo30** [comment]
In .h5 file,the z4-R6 marker position is (345,539), but after run_optical_flow it starts at 340 in x axis. Same thing with z4-R4, marker position is (308,539), but trajectory starts at 343.

![image](https://github.com/GazzolaLab/BR2-vision-based-smoothing/assets/86000876/9c89fc95-699b-4374-a901-46c3b189b976)

![image](https://github.com/GazzolaLab/BR2-vision-based-smoothing/assets/86000876/2173bac7-57b3-47a8-abce-a235d34a6ba8)

**Comment by skim0119** [comment]
Resolved with latest commits. Unittest included.
