### ISSUE TITLE
Set_optical_flow for multiple frames

### ISSUE THREAD

**Issue by davidmelchor28** [GazzolaLab/BR2-vision-based-smoothing#8]
run_optical_flow fails when setting points at different timestamps. You have to run it as many times as the number of edited timestamps. This wastes some time when post-processing.

![image](https://github.com/GazzolaLab/BR2-vision-based-smoothing/assets/129805357/8ee4a9ec-f135-4ab4-ac4b-55f0cd8b2840)
![image](https://github.com/GazzolaLab/BR2-vision-based-smoothing/assets/129805357/c17077e6-45f2-48b6-80bf-97b222abb0fa)

**Comment by skim0119** [comment]
Okay, this is definitely not expected behavior. I'll fix it

**Comment by skim0119** [comment]
Should be resolved with: https://github.com/GazzolaLab/BR2-vision-based-smoothing/commit/8c23efe94cf9a76cd0069cc29edad0ba94a6eda0
