### ISSUE TITLE
Optical flow tracking fails when a point crosses a camera seen in the background

### ISSUE THREAD

**Issue by davidmelchor28** [GazzolaLab/BR2-vision-based-smoothing#9]
As the title explains, optical flow fails to track a point that crosses a camera seen in the background. It quickly moves to a different position and moves over time for no reason. Here are some attachments. The best way I could fix it was to set that point (z5 R3) from frames 0-70 and then set it again once past the camera (frame 90).
<img width="590" alt="image" src="https://github.com/GazzolaLab/BR2-vision-based-smoothing/assets/129805357/3db340a5-6152-4ddc-a370-5fd1de0579c7">
<img width="590" alt="image" src="https://github.com/GazzolaLab/BR2-vision-based-smoothing/assets/129805357/b0da0778-9e6e-4073-a2ac-de52e8293aad">
<img width="590" alt="image" src="https://github.com/GazzolaLab/BR2-vision-based-smoothing/assets/129805357/4e890a8d-65ce-476b-a8c5-89ae49049136">

**Comment by skim0119** [comment]
This is inherit problem of optical flow, there is not much of algorithmic improvement that can be done. I'm adding manual way of tracing the point as alternative.
